/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ElectionContract } from "./Election";
import { MainContractContract } from "./MainContract";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Election"): ElectionContract;
      require(name: "MainContract"): MainContractContract;
    }
  }
}

export { ElectionContract, ElectionInstance } from "./Election";
export { MainContractContract, MainContractInstance } from "./MainContract";
